<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Knight - Free Bootstrap 4 Product Landing Page Template</title>
    <meta name="description"
          content="Knight is a beautiful Bootstrap 4 template for product landing pages."/>

    <!--Inter UI font-->
    <link href="https://rsms.me/inter/inter-ui.css" rel="stylesheet">

    <!--vendors styles-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css">

    <!-- Bootstrap CSS / Color Scheme -->
    <link rel="stylesheet" href="css/default.css" id="theme-color">
</head>
<body>

<!--navigation-->
<section class="smart-scroll">
    <div class="container-fluid">
        <nav class="navbar navbar-expand-md navbar-dark">
            <a class="navbar-brand heading-black" href="index.php">
            <img src="img/unnamed (1).png" class="img-fluid rounded d-block mx-auto" alt="Work 1" width="150px"/>
            </a>
            <button class="navbar-toggler navbar-toggler-right border-0" type="button" data-toggle="collapse"
                    data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span data-feather="grid"></span>
            </button>
            
            <?php $link_address1 = 'iindex.php';


$link_address2 = 'SPECIALISTS.php';
$link_address3 = 'Contact.php'; ?> 
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="#features">About </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="#faq">countuct us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="#faq">FAQ</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link page-scroll" href="#pricing">pricing</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link page-scroll d-flex flex-row align-items-center text-primary" href="iindex.php">
                            <em data-feather="layout" width="18" height="18" class="mr-2"></em>
                            LOGIN
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</section>

<!--hero header-->
<section class="py-7 py-md-0 bg-hero" id="home">
    <div class="container">
        <div class="row vh-md-100">
            <div class="col-md-8 col-sm-10 col-12 mx-auto my-auto text-center">
                <h2 class="heading-black text-capitalize">Broken links are bad for business.
Let Dr. Link Check track them down for you.</h2>
                
               <a href="check/check.php"> <button class="btn btn-primary d-inline-flex flex-row align-items-center">
                    Get started now
                    <em class="ml-2" data-feather="arrow-right"></em>
                </button></a>
            </div>
        </div>
    </div>
</section>

<!-- features section -->
<section class="pt-6 pb-7" id="features">
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto text-center">
                <h2 class="heading-black">Easily find broken and malicious links</h2>
                <p class="text-muted lead">n that ours is an extension that is installed in the browser. Therefore, it will be faster and easier to use, because it has already been installed. It does not require the user to reveal the links each time it searches or has have to visit the website, which makes it distinct from similar applications. SSL, TLS, and HTTPS are present on the website
</p>
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-md-10 mx-auto">
                <div class="row feature-boxes">
                    <div class="col-md-6 box">
                        <div class="icon-box box-primary">
                            <div class="icon-box-inner">
                                <span data-feather="edit-3" width="35" height="35"></span>
                            </div>
                        </div>
                        <h5>You can write any link.</h5>
                       
                    </div>
                    <div class="col-md-6 box">
                        <div class="icon-box box-success">
                            <div class="icon-box-inner">
                                <span data-feather="monitor" width="35" height="35"></span>
                            </div>
                        </div>
                        <h5>Unlimited devices</h5>
                     
                    </div>
                   
                    <div class="col-md-6 box">
                        <div class="icon-box box-info">
                            <div class="icon-box-inner">
                                <span data-feather="globe" width="35" height="35"></span>
                            </div>
                        </div>
                        <h5>Available globally</h5>
                      
                    </div>
                </div>
            </div>
        </div>
        <div class="row mt-6">
            <div class="col-md-6 mr-auto">
                <h2>Easily find broken and malicious links</h2>
                <p class="mb-5">Non-working links are annoying and reflect poorly on your professionalism. They not only deter visitors from staying on and returning to your site, but they can also negatively impact your search engine rankings. Even worse than a broken link is a link to a website that causes harm through malware or phishing.

Instead of manually checking all the pages of your site and clicking through all the outgoing links, let we check Check do the work and give you a report of the links that need your attention.</p>
                <a href="#" class="btn btn-light">
                    Try
                </a>
            </div>
            <div class="col-md-5">
                <div class="slick-about">
                    <img src="img/vcc.jpg" class="img-fluid rounded d-block mx-auto" alt="Work 1"/>
                    <img src="img/cc.jpg" class="img-fluid rounded d-block mx-auto" alt="Work 2"/>
                    <img src="img/bb.jpg" class="img-fluid rounded d-block mx-auto" alt="Work 3"/>
                </div>
            </div>
        </div>
    </div>
</section>

<!--pricing section-->
<section class="py-7 bg-dark section-angle top-right bottom-right" id="pricing">
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto text-center">
                <h2 class="text-white heading-black">Pricing</h2>
                <p class="text-light lead">How much does WECHECK Check cost?</p>
            </div>
        </div>
        <!--pricing tables-->
        <div class="row pt-5 pricing-table">
            <div class="col-12 mx-auto">
                <div class="card-deck pricing-table">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-title pt-3">FREE</h3>
                            <h2 class="card-title text-primary mb-0 pt-4">$0</h2>
                            <div class="text-muted font-weight-medium mt-2">per month</div>
                            <ul class="list-unstyled pricing-list">
                                <li>1 user</li>
                                <li>10 URL</li>
                                <li>Basic support</li>
                            </ul>
                            <a href="#" class="btn btn-primary">
                                Start free trial
                            </a>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
       
       
</section>

<!--faq section-->
<section class="py-7" id="faq">
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto text-center">
                <h2>Frequently asked questions</h2>
                <p class="text-muted lead">Answers to most common questions.</p>
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-md-10 mx-auto">
                <div class="row">
                    <div class="col-md-6 mb-5">
                        <h6>What counts as a link?</h6>
                        <p class="text-muted">Each unique HTML document, image, style sheet, script, or other resource referenced from your website counts as a link. If the same resource is linked from multiple pages, it still only counts as one link.</p>
                    </div>
                    <div class="col-md-6 mb-5">
                        <h6>How do I know how many links my website has?
                        </h6>
                        <p class="text-muted">Unfortunately, there’s no exact way to calculate the number of links beforehand. We recommend starting with a rough estimate and adjusting your subscription plan late</p>
                    </div>
                    <div class="col-md-6 mb-5">
                        <h6>How can I upgrade/downgrade/cancel my subscription?</h6>
                        <p class="text-muted">You can change or cancel your subscription at any time. Simply log in to your account, click on “Account” at the right-hand side of the title bar, and select “Subscription Settings” from the drop-down menu to see the available options.</p>
                    </div>
                    <div class="col-md-6 mb-5">
                        <h6>Will I be charged VAT/Sales Tax?</h6>
                        <p class="text-muted">If you have a VAT ID, be sure to enter it via the “Add VAT Number” link on the checkout page. This will avoid unnecessary VAT charges.</p>
                    </div>
                    <div class="col-md-6 mb-5">
                        <h6>Will I receive an invoice?
                        </h6>
                        <p class="text-muted">You will receive an invoice for every payment made via email. Each invoice will include VAT (Sales Tax) where applicable.

                        </p>
                    </div>
                    <div class="col-md-6 mb-5">
                        <h6>How do I know how many links my website has?
                        </h6>
                        <p class="text-muted">Unfortunately, there’s no exact way to calculate the number of links beforehand. We recommend starting with a rough estimate and adjusting your subscription plan later, once you hit the link limit or find that you have too much unused quota. You can upgrade or downgrade your subscription at any time without penalty.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-md-6 mx-auto text-center">
                <h5 class="mb-4">Have questions?</h5>
                <a href="Contact.html" class="btn btn-primary">Contact us</a>
            </div>
        </div>
    </div>
</section>

<!--footer-->
<footer class="py-6">
    <div class="container">
        <div class="row">
            <div class="col-sm-5 mr-auto">
                <h5>About we check</h5>
                <p class="text-muted">n that ours is an extension that is installed in the browser. Therefore, it will be faster and easier to use, because it has already been installed. It does not require the user to reveal the links each time it searches or has have to visit the website, which makes it distinct from similar applications. SSL, TLS, and HTTPS are present on the website
.</p>


                <ul class="list-inline social social-sm">
                    <li class="list-inline-item">
                        <a href=""><i class="fa fa-facebook"></i></a>
                    </li>
                    <li class="list-inline-item">
                        <a href=""><i class="fa fa-twitter"></i></a>
                    </li>
                    <li class="list-inline-item">
                        <a href=""><i class="fa fa-google-plus"></i></a>
                    </li>
                    <li class="list-inline-item">
                        <a href=""><i class="fa fa-dribbble"></i></a>
                    </li>
                </ul>
            </div>
            <div class="col-sm-2">
 
                <h5>Legal</h5>
                <ul class="list-unstyled">
                    <li><a href="#">Privacy</a></li>
                    <li><a href="#">Terms</a></li>
                </ul>
            </div>
            <div class="col-sm-2">
                <h5>Partner</h5>
                <ul class="list-unstyled">
                    <li><a href="#">Refer a friend</a></li>
                </ul>
            </div>
            <div class="col-sm-2">
                <h5>Help</h5>
                <ul class="list-unstyled">
                    <li><a href="#">Support</a></li>
                    <li><a href="iindex.php">Log in</a></li>
                </ul>
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-12 text-muted text-center small-xl">
                &copy; 2023 WECHECK - All Rights Reserved
            </div>
        </div>
    </div>
</footer>

<!--scroll to top-->
<div class="scroll-top">
    <i class="fa fa-angle-up" aria-hidden="true"></i>
</div>

<!-- theme switcher (FOR DEMO ONLY - REMOVE FROM PRODUCTION)-->
<div class="switcher-wrap">
    <div class="switcher-trigger">
        <span class="fa fa-gear"></span>
    </div>
    <div class="color-switcher">
        <h6>Color Switcher</h6>
        <ul class="mt-3 clearfix">
            <li class="bg-teal active" data-color="default" title="Default Teal"></li>
            <li class="bg-purple" data-color="purple" title="Purple"></li>
            <li class="bg-blue" data-color="blue" title="Blue"></li>
            <li class="bg-red" data-color="red" title="Red"></li>
            <li class="bg-green" data-color="green" title="Green"></li>
            <li class="bg-indigo" data-color="indigo" title="Indigo"></li>
            <li class="bg-orange" data-color="orange" title="Orange"></li>
            <li class="bg-cyan" data-color="cyan" title="Cyan"></li>
            <li class="bg-yellow" data-color="yellow" title="Yellow"></li>
            <li class="bg-pink" data-color="pink" title="Pink"></li>
        </ul>
        <p>These are just demo colors. You can <b>easily</b> create your own color scheme.</p>
    </div>
</div>

<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.7.3/feather.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"></script>
<script src="js/scripts.js"></script>
</body>
</html>